imports:
  # PubSub
  - path: templates/pubsub-particle.jinja
    name: pubsub-particle-template.jinja
  # BigQuery
  - path: templates/bigquery-telemetry.jinja
    name: bigquery-telemetry-template.jinja
  # Storage
  - path: templates/storagebucket.jinja
    name: storage-template.jinja
  # Functions
  - path: templates/cloudfunction.py
    name: function-template.py
  - path: function/*/*


resources:
  # Create our BigQuery telemetry table
  - name: bigquery-telemetry-table
    type: bigquery-telemetry-template.jinja
    properties:
      datasetName: telemetry_dataset
      tableName: telemetry_table
      region: US
  # Instantiate the topic and add a service account to it
  - name: particle-pubsub
    type: pubsub-particle-template.jinja
    properties:
      topic: particle-endpoint
      subscriptionRole: roles/pubsub.publisher
      subscriptionMember: serviceAccount:particle-public@particle-public.iam.gserviceaccount.com
  # Set up our storage bucket to upload function code to
  - name: code-storage
    type: storage-template.jinja
    properties:
      bucketBase: code-storage
      region: US
      storageClass: STANDARD
  # Particle to BigQuery function (WIP, TODO)
  - name: particle-to-bigquery-function
    type: function-template.py
    properties:
      codeLocation: function/particle-to-bigquery/
      bucketBase: code-storage
      location: us-central1
      timeout: 60s
      runtime: nodejs14
      availableMemoryMb: 256
      entryPoint: handler
      environmentVariables:
        datasetName: $(ref.bigquery-telemetry-table.datasetName)
        tableName: $(ref.bigquery-telemetry-table.tableName)
      eventTrigger:
        resource: $(ref.particle-pubsub.topicName)
        eventType: providers/cloud.pubsub/eventTypes/topic.publish
  # # BigQuery proxy
  - name: bigquery-proxy-function
    type: function-template.py
    properties:
      codeLocation: function/bigquery-proxy/
      bucketBase: code-storage
      location: us-central1
      timeout: 60s
      runtime: nodejs14
      availableMemoryMb: 256
      entryPoint: handler
      httpsTrigger: true
      publicAccess: true
